In [ ]:
Exercicios de Python Let's Code Basic

In [2]:
## Faça um programa que peça um valor monetário e diminua-o em 15%. Seu programa 
## deve imprimir a mensagem “O novo valor é [valor]”.

valor = float(input('Digite o valor: '))

novo_val = valor * 0.15

print(f'O novo valor é {novo_val:.2f}') 

Digite o valor:  500


O novo valor é 75.00


In [ ]:
#Criando um algoritmo usando if (simulação de corrida x onibus)

valor_passagem =  4.30

valor_corrida = float(input('Digite o valor da corrida: '))

if valor_corrida <= valor_passagem * 3:
  print('Pague a corrida')
elif valor_corrida <= valor_passagem * 4:
  print('Aguarde o valor pode abaixar')
else:
  print('Vai de onibus')

Digite o valor da corrida: 14.0
Aguarde o valor pode abaixar


In [ ]:
#Exe Contador
contador = 0
#Definindo o numero de repetição
numero = int(input('Digite um numero: '))
#Rodando a estrutura de repetição
while contador < numero:
  print(contador)
  contador += 1

Digite um numero: 10
0
1
2
3
4
5
6
7
8
9


In [ ]:
# Exe While (sistema de senhas)

senha = input('Criar senha: ')
print('Senha criada com sucesso')

Criar senha: 94563381
Senha criada com sucesso


In [ ]:
dig_senha = input('Digite sua senha: ')

while senha != dig_senha:
    dig_senha = input('Senha invalida. Tente novamente: ')

print('Acesso permitido')

Digite sua senha: wendell
Senha invalida. Tente novamente958662
Senha invalida. Tente novamente9456338
Senha invalida. Tente novamente94563381
Acesso permitido


In [ ]:
## Sistema de cadastro
## Cadastre os valores no banco de dados


In [ ]:
"""Faça um programa que leia a validade das informações:
a. Idade: entre 0 e 150;
b. Salário: maior que 0;
c. Sexo: M, F ou Outro;
O programa deve imprimir uma mensagem de erro para cada informação inválida."""

idade = int(input('Digite sua idade: '))

if idade > 0 and idade < 100:
    print('Idade cadastrada')
else:
    print('Idade invalida')

salario = float(input('Digite seu salário: '))

if salario > 0:
    print('Salário cadastrado')
else:
    print('Salário invalido')

sexo = input('Sexo M | F: ')

if sexo != 'M' and sexo != 'F':
    print('Sexo invalido')
else:
    print('Sexo cadastrado')

print('Dados cadastro com sucesso')



Digite sua idade: 180
Idade invalida
Digite seu salário: 0
Salário invalido
Sexo M | F: a
Sexo invalido
Dados cadastro com sucesso


In [ ]:
"""Vamos fazer um programa para verificar quem é o assassino de um crime.
Para descobrir o assassino, a polícia faz um pequeno questionário com 5
perguntas onde a resposta só pode ser sim ou não:

a. Mora perto da vítima?
b. Já trabalhou com a vítima?
c. Telefonou para a vítima?
d. Esteve no local do crime?
e. Devia para a vítima?

Cada resposta sim dá um ponto para o suspeito. A polícia considera que os
suspeitos com 5 pontos são os assassinos, com 4 a 3 pontos são cúmplices e
2 pontos são apenas suspeitos, necessitando outras investigações. Valores
iguais ou abaixo de 1 são liberados."""



In [ ]:
"""Faça um programa que imprima a tabuada do 9 (de 9*1 a 9*10) usando loops."""



In [ ]:
"""
salario_mensal = float(input('Digite o valor do salario: '))
gastos_mensal = float(input('Digite o valor gasto mensal em média: '))

tot_salario =  salario_mensal * 12
tot_gastos = gastos_mensal * 12

lucro = tot_salario - tot_gastos

print(f'Sua renda anual foi de R${tot_salario:.2f} reais')
print(f'Seus gastos anual foi de R${tot_gastos:.2f} reais')
print(f'Seu lucro anual foi de R${lucro:.2f} reais')
"""

Digite o valor do salario: 2310
Digite o valor gasto mensal em média: 850
Sua renda anual foi de R$27720.00 reais
Seus gastos anual foi de R$10200.00 reais
Seu lucro anual foi de R$17520.00 reais


In [ ]:
"""Faça um Programa que peça as 4 notas bimestrais e mostre a média."""


In [ ]:
nome = input('Digite seu nome: ')
idade = int(input('Digite sua idade: '))
covid = input('Tem sintomas do Covid: ').upper()

if idade >= 65:
    print(f'O paciênte {nome} possui atendimento prioritário')
elif covid == 'SIM':
    print(f'O paciênte {nome} deve ser levado para a sala reservada')
else:
    print(f'O paciênte {nome} pode esperar na sala comum')

Sigite seu nome: jose
Digite sua idade: 20
Tem sintomas do Covid: sim
O paciênte jose pode esperar na sala comum


In [ ]:
"""
Faça um programa para uma loja de tintas.

O programa deverá pedir  tamanho em metros quadrados da área a ser pintada.
Considere que a cobertudra da tinta é de 1 litro para cada 3 metros quadrados
e que a tinta é vendida em latas de 18 litros , que custam R$ 80,00.

Informe ao usuário a quantidades de latas de tinta a serem compradas e o preço total.
"""

#********************SUPER TINTAS************************

print('Compre sua tinta na SUPER TINTAS\n')
area = int(input('Digite a área a ser pintada: '))

litro = area // 3
if area % 3 > 0:
    litro = litro + 1

latas = litro // 18
if litro % 18 > 0:
    latas = latas + 1

print("você precisara de",latas,'latas')
print('Valor:',latas*80)


Compre sua tinta na SUPER TINTAS



In [ ]:
"""Contator"""

numero = int(input('Digite um número: '))
while numero <= 100:
    print(numero)
    numero += 1


Digite um número: 90
90
91
92
93
94
95
96
97
98
99
100


In [ ]:
#Tabuada

tabuada = int(input('Digite o numero da tabuada: '))

for x in range(1,11,1):
    print(f'{tabuada} x {x} = {tabuada*x}')

Digite o numero da tabuada: 5
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


In [ ]:
import os #Biblioteca para uso do cls

In [ ]:
#USO DE LISTA SISTEMA DE INVENTARIO

#Cadastro no inventario

inventario =[]
resposta ='S'
while resposta == 'S':
    inventario.append(input('Equipamento: '))
    inventario.append(float(input('Valor: ')))
    inventario.append(int(input('Nº serial: ')))
    inventario.append(input('Departamento: '))
    resposta = input('Digite S para continuar: ').upper()
    os.system('clear') or None


Equipamento: Notebook Dell
Valor: 3599.99
Nº serial: 54668225
Departamento: Informatica
Digite S para continuar: n


In [ ]:
for x in inventario:
    print(x)

Notebook Dell
3599.99
54668225
Informatica


In [ ]:
#1- Faça um Programa que peça dois números e imprima o maior deles.

n1 = int(input('Digite o 1º número: '))
n2 = int(input('Digite o 2º número: '))

if n1 > n2:
    print(f'O maior número é {n1}')
else:
    print(f'O maior número é {n2}')

Digite o 1º número: 542
Digite o 2º número: 8852
O maior número é 8852


In [ ]:
#2- Faça um Programa que peça um valor e mostre na tela se o valor é positivo ou negativo.

x = int(input('Digite um numero: '))

if x > 0:
    print(f'O numero {x} é positivo')
else:
    print(f'O numero {x} é negativo')

Digite um numero: -44
O numero -44 é negativo


In [ ]:
#3 Faça um Programa que verifique se uma letra digitada é "F" ou "M". 
#Conforme a letra escrever: F - Feminino, M - Masculino, Sexo Inválido.

sexo = input('Digite o sexo: ').upper()
if sexo == 'F':
    print('Feminino')
elif sexo == 'M':
    print('Masculino')
else:
    print('Sexo invalido')

Digite o sexo: e
Sexo invalido


In [ ]:
#4 Faça um Programa que verifique se uma letra digitada é vogal ou consoante.


In [ ]:
"""5 Faça um programa para a leitura de duas notas parciais de um aluno. 
O programa deve calcular a média alcançada por aluno e apresentar:

    A mensagem "Aprovado", se a média alcançada for maior ou igual a sete;
    A mensagem "Reprovado", se a média for menor do que sete;
    A mensagem "Aprovado com Distinção", se a média for igual a dez. """

nota1 = float(input('1º Nota: '))
nota2 = float(input('2º Nota: '))

media = (nota1 + nota2) / 2
if media >= 7:
    print(f'Aprovado, média {media}')
elif media < 7:
    print(f'Reprovado, média {media}')
elif media == 10:
    print(f'Aprovado com distinção, média {media}')

In [ ]:
#6 Faça um Programa que leia três números e mostre o maior deles. 

n1 = int(input('Digite o 1º número: '))
n2 = int(input('Digite o 2º número: '))
n3 = int(input('Digite o 3º número: '))

if n1 > n2 and n1 > n3:
    print(f'O maior número é {n1}')
if n2 > n1 and n2 > n3:
    print(f'O maior número é {n2}')
else:
    print(f'O maior número é {n3}') 

In [ ]:
#7 Faça um Programa que leia três números e mostre o maior e o menor deles.
n1 = int(input('Digite o 1º número: '))
n2 = int(input('Digite o 2º número: '))
n3 = int(input('Digite o 3º número: '))

if n1 > n2 and n1 > n3:
    print(f'O maior número é {n1}')
if n2 > n1 and n2 > n3:
    print(f'O maior número é {n2}')
else:
    print(f'O maior número é {n3}')

if n1 < n2 and n1 < n3:
    print(f'O menor número é {n1}')
if n2 < n1 and n2 < n3:
    print(f'O menor número é {n2}')
else:
    print(f'O menor número é {n3}')

In [ ]:
#8 Faça um programa que pergunte o preço de três produtos e informe qual produto você deve comprar, sabendo que a decisão é sempre pelo mais barato.
prd1 = float(input('Digite o valor do 1º produto: '))
prd2 = float(input('Digite o valor do 2º produto: '))
prd3 = float(input('Digite o valor do 3º produto: '))

if prd1 < prd2 and prd1 < prd3:
    print(f'O valor mais barato do produto é {prd1}')
if prd2 < prd1 and prd2 < prd3:
    print(f'O valor mais barato do produto é {prd2}')
else:
    print(f'O valor mais barato do produto é {prd3}')

In [ ]:
#9 Faça um Programa que leia três números e mostre-os em ordem decrescente.


In [ ]:
#10 Faça um Programa que pergunte em que turno você estuda. Peça para digitar M-matutino ou V-Vespertino ou N- Noturno. Imprima a mensagem "Bom Dia!", "Boa Tarde!" ou "Boa Noite!" ou "Valor Inválido!", conforme o caso.

turno = input('Digite seu turno ("M"-Matutino, "V"-Vespertino, "N"-Noturno); ').upper()

if turno == 'M':
        print('Bom Dia!')
elif turno == 'V':\
        print('Boa Tarde!')
elif turno == 'N': \
        print('Boa Noite')
else:
        print('Valor invalido')



In [ ]:

'''11 As Organizações Tabajara resolveram dar um aumento de salário aos seus colaboradores e lhe contraram para desenvolver o programa que calculará os reajustes.

    Faça um programa que recebe o salário de um colaborador e o reajuste segundo o seguinte critério, baseado no salário atual:
    salários até R$ 280,00 (incluindo) : aumento de 20%
    salários entre R$ 280,00 e R$ 700,00 : aumento de 15%
    salários entre R$ 700,00 e R$ 1500,00 : aumento de 10%
    salários de R$ 1500,00 em diante : aumento de 5% Após o aumento ser realizado, informe na tela:
    o salário antes do reajuste;
    o percentual de aumento aplicado;
    o valor do aumento;
    o novo salário, após o aumento. '''

#Curso Python Basico - Ignorancia Zero

In [ ]:
#Ex - Organize os numero 2,3,4,5,10,12 para obter a saida 18 em uma unica operação:

x = 12*3
x = x+4
x = x//10
x = x*5
x = x-2
#print(x) - Resultado 18

x = (5*((4+(12*3))//10))-2
print(x) ## Resultado em uma unica operação

18


In [ ]:
# Cndição IF/ELSE

idade = int(input('Qual a sua idade? '))

if idade >= 18:
    print('Hora de beber!')
else:
    print('Pra você somente Toddynho!')

Qual a sua idade? 22
Hora de beber!


In [ ]:
# EX 3
'''O programa deverá pedir o tamanho em metros quadrados da área a ser pintada. Considere que a cobertura da tinta é de 1 litro para cada
6 metros quadrados e que a tinta é vendida em latas de 18 litros, que custam R$ 80,00 ou em galões de 4 litros, que custam R$ 25,00'''

'''Informe o usuário as quantidades de tinta a serem compradas e os respectivos preços em 3 situações: comprar apenas latas de 18 litros,
comprar apenas galões de 4 litros, misturar latas e galões de forma que o preço seja menor'''

area = int(input("Insira o valor da área: "))

# Vamos calcular o numero de litros necessários para pintar a casa
litros = area // 6
if area % 6 > 0:
    litros = litros + 1

print("Litros necessários:", litros, "\n")

print("1) comprar apenas latas de 18 litros")
latas = litros // 18
if litros % 18 > 0:
    latas = latas + 1

print("Serão necessárias", latas, "latas")
print("Obteremos", latas * 18, "litros")
print("Total: R$", latas * 80)

print("\n2)Comprar apenas galões de 4 litros")
galoes = litros//4
if litros % 4 > 0:
    galoes = galoes + 1

print("Serão necessárias", galoes, "galoes")
print("Obteremos", galoes * 4, "litros")
print("Total: R$", galoes * 25)

# Vamos pensar, o preço total por litro pago nas latas é 80/18 ~ 4.44 R$/L
# enquanto que para o gualão é 25/4 ~ 6.25 R$/L
# portanto é sempre mais vantajoso comprar o máximo de latas possíveis
# e o mínimo de galões, desde que o preço desses galoes não ultrapasse o preço
# de uma lata, isto é, o numero de galoes seja menor ou igual a 3 (R$ 75)
print("\n3)Misturar latas e galões, de forma que o preço seja o menor.")
latas = litros // 18
galoes = 0
litros_restantes = litros % 18

if litros_restantes <= 3 * 4:
    # Ou seja o numero de galoes necessarios seja menor do que três
    galoes = litros_restantes // 4
    if litros_restantes % 4 > 0:
        galoes += 1
else:
    latas += 1

print("Serão necessárias", latas, "latas")
print("Serão necessárias", galoes, "galoes")
print("Obteremos", latas * 18 + galoes * 4, "litros")
print("Total: R$", galoes * 25 + latas * 80)

In [ ]:
#EX 3.1 Faça um Programa que peça dois números e imprima o maior deles. 

n1 = int(input('Digite 1º numero: '))
n2 = int(input('Digite 2º numero: '))

if n1 > n2:
    print(f'O maior número é o {n1}')
else:
    print(f'O maior número é o {n2}')

Digite 1º numero: -5
Digite 2º numero: 3
O maior número é o 3


In [ ]:
#EX 3.2 Faça um Programa que peça um valor e mostre na tela se o valor é positivo ou negativo.

p1 = int(input('Digite 1º numero: '))

if p1 > 0:
    print(f'{p1} é positivo')
else:
    print(f'{p1} é negativo')

Digite 1º numero: 20
20 é positivo


In [ ]:
#EX 3.3 Faça um Programa que verifique se uma letra digitada é "F" ou "M". Conforme a letra escrever: F - Feminino, M - Masculino, Sexo Inválido.

sexo = input('Sexo (F) / (M):')

if sexo == 'F':
    print('Feminino')
elif sexo == 'M':
    print('Masculino')
else:
    print('Sexo Invalido')

Sexo (F) / (M):F
Feminino


In [ ]:
#EX3.4 Faça um Programa que verifique se uma letra digitada é vogal ou consoante. 

vogal = input('Digite uma letra vogal ou consoante: ')

if vogal == 'a' or vogal == 'A':
    print('Vogal')
elif vogal == 'e' or vogal == 'E':
    print('Vogal')
elif vogal == 'i' or vogal == 'I':
    print('Vogal')
elif vogal == 'o' or vogal == 'O':
    print('Vogal')
elif vogal == 'u' or vogal == 'U':
    print('Vogal')
else:
    print('Consoante')


Digite uma letra vogal ou consoante: A
Vogal


In [ ]:
#EX3.5 Faça um programa para a leitura de duas notas parciais de um aluno. O programa deve calcular a média alcançada por aluno e apresentar:

    #A mensagem "Aprovado", se a média alcançada for maior ou igual a sete;
    #A mensagem "Reprovado", se a média for menor do que sete;
    #A mensagem "Aprovado com Distinção", se a média for igual a dez. 

nota1 = int(input('1ª Nota: '))
nota2 = int(input('2ª Nota: '))

media = (nota1 + nota2)/2

if media >= 10:
    print(f'Media {media} - Aprovado com Distinção')
elif media >= 7:
    print(f'Media {media} - Aprovado')
else:
    print(f'Media {media} - Reprovado')


1ª Nota: 8
2ª Nota: 2
Media 5.0 - Reprovado


In [ ]:
#EX3.6 Faça um Programa que leia três números e mostre o maior deles.

nu1 = int(input('Digite 1º número: '))
nu2 = int(input('Digite 2º número: '))
nu3 = int(input('Digite 3º número: '))

if nu1 > nu2 and nu1 > nu3:
    print(f'O maior número é {nu1}')
elif nu2 > nu1 and nu2 > nu3:
    print(f'O maior número é {nu2}')
else:
    print(f'O maior número é {nu3}')

Digite 1º número: 5
Digite 2º número: 4
Digite 3º número: 15
O maior número é 15


In [ ]:
#EX3.7 Faça um Programa que leia três números e mostre o maior e o menor deles.
nu1 = int(input('Digite 1º número: '))
nu2 = int(input('Digite 2º número: '))
nu3 = int(input('Digite 3º número: '))

if nu1 > nu2 and nu1 > nu3:
    print(f'O maior número é {nu1}')
elif nu2 > nu1 and nu2 > nu3:
    print(f'O maior número é {nu2}')
else:
    print(f'O maior número é {nu3}')

if nu1 < nu2 and nu1 < nu3:
    print(f'O menor número é {nu1}')
elif nu2 > nu1 and nu2 < nu3:
    print(f'O menor número é {nu2}')
else:
    print(f'O menor número é {nu3}')

Digite 1º número: 8
Digite 2º número: 4
Digite 3º número: 2
O maior número é 8
O menor número é 2


In [ ]:
'''EX3.8 Faça um programa que pergunte o preço de três produtos e informe qual produto você deve comprar, 
   sabendo que a decisão é sempre pelo mais barato. '''

prod1 = float(input('Digite o valor do produto: '))
prod2 = float(input('Digite o valor do produto: '))
prod3 = float(input('Digite o valor do produto: '))

if prod1 < prod2 and prod1 < prod3:
    print(f'O valor do produto mais barato é {prod1}')
elif prod2 < prod1 and prod2 < prod3:
    print(f'O valor do produto mais barato é {prod2}')
else:
    print(f'O valor do produto mais barato é {prod3}')


Digite o valor do produto: 19.50
Digite o valor do produto: 144
Digite o valor do produto: 84.80
O valor do produto mais barato é 19.5


In [ ]:
'''EX3.9 As Organizações Tabajara resolveram dar um aumento de salário aos seus colaboradores e lhe contraram para desenvolver o 
   programa que calculará os reajustes.

    Faça um programa que recebe o salário de um colaborador e o reajuste segundo o seguinte critério, baseado no salário atual:
    salários até R$ 280,00 (incluindo) : aumento de 20%
    salários entre R$ 280,00 e R$ 700,00 : aumento de 15%
    salários entre R$ 700,00 e R$ 1500,00 : aumento de 10%
    salários de R$ 1500,00 em diante : aumento de 5% Após o aumento ser realizado, informe na tela:
    o salário antes do reajuste;
    o percentual de aumento aplicado;
    o valor do aumento;
    o novo salário, após o aumento. '''


salario = float(input('Digite o salário a ser ajustado: '))

if salario >= 1500:
    aum = salario * 0.05
    print(f'Salário: {salario:.2f}')
    print('5% de aumento')
    print(f'Valor do aumento: {aum:.2f}')
    print(f'Novo Salário: {salario+aum:.2f}')
elif salario > 700:
    aum = salario * 0.10
    print(f'Salário: {salario:.2f}')
    print('10% de aumento')
    print(f'Valor do aumento: {aum:.2f}')
    print(f'Novo Salário: {salario+aum:.2f}')
elif salario > 280:
    aum = salario * 0.15
    print(f'Salário: {salario:.2f}')
    print('15% de aumento')
    print(f'Valor do aumento: {aum:.2f}')
    print(f'Novo Salário: {salario+aum:.2f}')
else:
    aum = salario * 0.20
    print(f'Salário: {salario:.2f}')
    print('20% de aumento')
    print(f'Valor do aumento: {aum:.2f}')
    print(f'Novo Salário: {salario+aum:.2f}')


Digite o salário a ser ajustado: 190
Salário: 190.00
20% de aumento
Valor do aumento: 38.00
Novo Salário: 228.00


In [ ]:
'''EX3.10 Faça um programa para o cálculo de uma folha de pagamento, sabendo que os descontos são do Imposto de Renda, 
que depende do salário bruto (conforme tabela abaixo) e 3% para o Sindicato e que o FGTS corresponde a 11% do Salário Bruto, 
mas não é descontado (é a empresa que deposita). O Salário Líquido corresponde ao Salário Bruto menos os descontos. 
O programa deverá pedir ao usuário o valor da sua hora e a quantidade de horas trabalhadas no mês.

    Desconto do IR:
    Salário Bruto até 900 (inclusive) - isento
    Salário Bruto até 1500 (inclusive) - desconto de 5%
    Salário Bruto até 2500 (inclusive) - desconto de 10%
    Salário Bruto acima de 2500 - desconto de 20% Imprima na tela as informações, dispostas conforme o exemplo abaixo. 
    No exemplo o valor da hora é 5 e a quantidade de hora é 220. 

        Salário Bruto: (5 * 220)        : R$ 1100,00
        (-) IR (5%)                     : R$   55,00  
        (-) INSS ( 10%)                 : R$  110,00
        FGTS (11%)                      : R$  121,00
        Total de descontos              : R$  165,00
        Salário Liquido                 : R$  935,00  '''

#Calculo da folha de pagamento e imposto de renda

sal = float(input('Salário: '))

if sal > 2500:
    valor_hora = sal / 220
    desc_IR = sal * 0.20
    desc_INSS = sal * 0.10
    fgts = sal * 0.11
    val_desc = desc_IR + desc_INSS
    print(f'Salário Bruto: ({valor_hora:.2f} * 220)     : R$ {sal:.2f}')
    print(f'(-) IR (20%)                     : R$ {desc_IR:.2f}')
    print(f'(-) INSS ( 10%)                  : R$ {desc_INSS:.2f}')
    print(f'FGTS (11%)                       : R$ {fgts:.2f}')
    print(f'Total de descontos               : R$ {val_desc:.2f}')
    print(f'Salário Liquido                  : R$ {sal - val_desc:.2f}')
elif sal > 1500:
    valor_hora = sal / 220
    desc_IR = sal * 0.10
    desc_INSS = sal * 0.10
    fgts = sal * 0.11
    val_desc = desc_IR + desc_INSS
    print(f'Salário Bruto: ({valor_hora:.2f} * 220)     : R$ {sal:.2f}')
    print(f'(-) IR (10%)                     : R$ {desc_IR:.2f}')
    print(f'(-) INSS ( 10%)                  : R$ {desc_INSS:.2f}')
    print(f'FGTS (11%)                       : R$ {fgts:.2f}')
    print(f'Total de descontos               : R$ {val_desc:.2f}')
    print(f'Salário Liquido                  : R$ {sal - val_desc:.2f}')
elif sal > 900:
    valor_hora = sal / 220
    desc_IR = sal * 0.05
    desc_INSS = sal * 0.10
    fgts = sal * 0.11
    val_desc = desc_IR + desc_INSS
    print(f'Salário Bruto: ({valor_hora:.2f} * 220)     : R$ {sal:.2f}')
    print(f'(-) IR (5%)                     : R$ {desc_IR:.2f}')
    print(f'(-) INSS ( 10%)                  : R$ {desc_INSS:.2f}')
    print(f'FGTS (11%)                       : R$ {fgts:.2f}')
    print(f'Total de descontos               : R$ {val_desc:.2f}')
    print(f'Salário Liquido                  : R$ {sal - val_desc:.2f}')
else:
    valor_hora = sal / 220
    desc_INSS = sal * 0.10
    fgts = sal * 0.11
    val_desc = desc_IR + desc_INSS
    print(f'Salário Bruto: ({valor_hora:.2f} * 220)     : R$ {sal:.2f}')
    print(f'(-) IR: Isento')
    print(f'(-) INSS ( 10%)                  : R$ {desc_INSS:.2f}')
    print(f'FGTS (11%)                       : R$ {fgts:.2f}')
    print(f'Total de descontos               : R$ {val_desc:.2f}')
    print(f'Salário Liquido                  : R$ {sal - val_desc:.2f}')

Salário: 2300
Salário Bruto: (10.45 * 220)     : R$ 2300.00
(-) IR (10%)                     : R$ 230.00
(-) INSS ( 10%)                  : R$ 230.00
FGTS (11%)                       : R$ 253.00
Total de descontos               : R$ 460.00
Salário Liquido                  : R$ 1840.00


In [ ]:
'''EX3.11 Faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As perguntas são:

    "Telefonou para a vítima?"
    "Esteve no local do crime?"
    "Mora perto da vítima?"
    "Devia para a vítima?"
    "Já trabalhou com a vítima?" O programa deve no final emitir uma classificação sobre a participação da pessoa no crime. 
     Se a pessoa responder positivamente a 2 questões ela deve ser classificada como "Suspeita", entre 3 e 4 como
    "Cúmplice" e 5 como "Assassino". Caso contrário, ele será classificado como "Inocente". '''



In [ ]:
'''EX3.12 Um posto está vendendo combustíveis com a seguinte tabela de descontos:

    Álcool:
    até 20 litros, desconto de 3% por litro
    acima de 20 litros, desconto de 5% por litro
    Gasolina:
    até 20 litros, desconto de 4% por litro
    acima de 20 litros, desconto de 6% por litro Escreva um algoritmo que leia o número de litros vendidos, 
    o tipo de combustível (codificado da seguinte forma: A-álcool, G-gasolina), calcule e imprima o valor a ser 
    pago pelo cliente sabendo-se que o preço do litro da gasolina é R$ 2,50 o preço do litro do álcool é R$ 1,90. '''

    

In [ ]:
'''EX3.13 Uma fruteira está vendendo frutas com a seguinte tabela de preços:

                          Até 5 Kg           Acima de 5 Kg
    Morango         R$ 2,50 por Kg          R$ 2,20 por Kg
    Maçã            R$ 1,80 por Kg          R$ 1,50 por Kg

    Se o cliente comprar mais de 8 Kg em frutas ou o valor total da compra ultrapassar R$ 25,00, 
    receberá ainda um desconto de 10% sobre este total. Escreva um algoritmo para ler a quantidade (em Kg) de morangos 
    e a quantidade (em Kg) de maças adquiridas e escreva o valor a ser pago pelo cliente. '''



In [ ]:
'''EX3.14 O Hipermercado Tabajara está com uma promoção de carnes que é imperdível. Confira:

                          Até 5 Kg           Acima de 5 Kg
    File Duplo      R$ 4,90 por Kg          R$ 5,80 por Kg
    Alcatra         R$ 5,90 por Kg          R$ 6,80 por Kg
    Picanha         R$ 6,90 por Kg          R$ 7,80 por Kg

    Para atender a todos os clientes, cada cliente poderá levar apenas um dos tipos de carne da promoção, 
    porém não há limites para a quantidade de carne por cliente. Se compra for feita no cartão Tabajara o cliente receberá 
    ainda um desconto de 5% sobre o total da compra. Escreva um programa que peça o tipo e a quantidade de carne comprada pelo 
    usuário e gere um cupom fiscal, contendo as informações da compra: tipo e quantidade de carne, preço total, tipo de pagamento, 
    valor do desconto e valor a pagar. '''



In [ ]:
# Bloco While

a = 0
while a < 5:
    print(a)
    a+= 1

0
1
2
3
4


In [ ]:
''' #Ex 4
Dizemos que um inteiro positivo n é perfeito se for igual à soma de seus divisores positivos diferentes de n.
Exemplo: 6 é perfeito, pois 1+2+3=6.
Dado um inteiro positivo n, verificar se n é perfeito'''

n = int(input("Digite o valor de n: "))

cont, soma = 2, 1
while cont < n:
    if n % cont == 0:
        soma += cont
    cont += 1

if soma == n:
    print ("O número", n, "é perfeito")
else:
    print ("O número", n, "não é perfeito")


In [ ]:
#EX 4.1  https://wiki.python.org.br/EstruturaDeRepeticao

In [ ]:
#EX 4.2  https://wiki.python.org.br/EstruturaDeRepeticao

In [ ]:
# Len - Usado para contar quantos caracteres tem na variavel mais usado em string e contrele de dados

#nome = 'Wendell Barcelos Albano Pestana'
#print(len(nome))

In [1]:
'''Sistema de cadastro de usuario'''

print('Cadastrar Usuario\n')
usuario = input('Criar usuario: ')
senha = input('Criar Senha: ')

if len(senha) < 8:
    print('Senha invalida minimo 8 caracteres')
else:
    print('\nUsuario cadastrado com sucesso')

Cadastrar Usuario


Usuario cadastrado com sucesso


In [2]:
'''Teste de cadastro de usuario'''

print('Entrar\n')

log_user = input('Usuario: ')
log_senha = input('Senha: ')

if log_user != usuario or log_senha != senha:
    print('\nUsuario ou senha invalido')
else:
    print('\nLogin efetuado com sucesso')

Entrar


Usuario ou senha invalido


In [ ]:
'''PASS E ELLIPS - São usadas quando necessario pular um bloco do codigo'''

valor = True

if valor:
    #print('Olá') ## Caso seja necessario pular um bloco para voltar depois sem apagar usar o pass ou ellips
    pass ## Usando o pass o codigo passar pela condição sem dar erro da msm forma usando ellips (...)
    ...
else:
    print('Tchau')


In [ ]:
'''MANIPULAÇÃO DE STRINGS E FUNÇÕES BUILT-IN (len, abs, type, print, etc)'''

# Indices de Strings

#Positivo -  [0123456]  ## O valor se inicia com 0
nome =       'Wendell'
#Negativo - -[7654321]  ## Usa o valor negativo sendo que o contador inicia no ultimo valor sendo 0 neutro
print(nome[3]) ## Vai ser exibido somente o valor que esta na posição 3

# Fatiamento de Strings - Usamos o fatiamento para remover algum valor unico de uma string.

url = 'http:www.facebook.com/' ## Para remover a barra na variavel url sera necessario usar o fatiamento
print(url)  ## Vai ser exibido o valor inicial
print(url[:-1])  ## Vai ser exibido a variavel porém sem o ultimo valor da string

# Usando fatiamento com indices [inicio:fim:passo] - para exibir o ultimo indice é necessario valor +1

print(url[5:21])  ## Vai ser exibido o valor da string iniciando pelo indice 5 e finalizando no 21 exibindo somente a url
print(url[:15])  ## Será exibido do indice 1 até o final sendo indice 15
print(url[:15:2]) ## Será exibido do indice 1 ate o indice 15 sendo o passo de 2 em 2

# Ler sobre as funções built-in e seus tipos
# https://docs.python.org/3/library/functions.html
# https://docs.python.org/3/library/stdtypes.html

d
http:www.facebook.com/
http:www.facebook.com
www.facebook.com
http:www.facebo
ht:w.aeo


In [ ]:
'''ESTRUTURA DE REPETIÇÃO WHILE - Usado para realizar ações ENQUANTO uma condição for verdadeira caso necessario o laço sendo infinito'''

#while True:  ## Essa estrutura vai gerar um loop infinito
    #nome = input('Qual é o seu nome? ')
    #print(f'Olá {nome}')

# Gerando um contador
x = 0  ## X no momento será zero
while x < 10:  ## Enquanto x for menor que 10 ele continua executando o codigo
    print(x)
    x = x + 1  ## Dada a expressões x soma o valor de +1 deixando de ser zero

# Usando o CONTINUE
x = 0  ## X no momento será zero
while x < 10:  ## Enquanto x for menor que 10 ele continua executando o codigo
    if x == 3:  ## Se x for igual a 3 
        x = x + 1  ## Soma mais 1 em x 
        continue  ## O uso do continue vai pular o valor da condição acima deixando 3 de fora do resultado
    print(x)
    x = x + 1

# Usando o BREAK
x = 0  ## X no momento será zero
while x < 10:  ## Enquanto x for menor que 10 ele continua executando o codigo
    if x == 3:  ## Se x for igual a 3 
        x = x + 1  ## Soma mais 1 em x 
        break  ## O uso do break ele finaliza o laço 
    print(x)
    x = x + 1

print('\n')

## Calculadora de multiplicação

x = int(input('Digite o valor a multiplicar: '))
y = 0  ## Usando acumuladores
z = 0  ## Usando acumuladores

while y <= 10:
    print(f'{x} x {y}: {z}')
    y += 1  ## Usando acumuladores
    z = x * y


0
1
2
3
4
5
6
7
8
9
0
1
2
4
5
6
7
8
9
0
1
2


Digite o valor a multiplicar: 2
2 x 0: 0
2 x 1: 2
2 x 2: 4
2 x 3: 6
2 x 4: 8
2 x 5: 10
2 x 6: 12
2 x 7: 14
2 x 8: 16
2 x 9: 18
2 x 10: 20


In [ ]:
'''ITERANDO SOBRE INDICES COM ESTRUTURA WHILE'''

frase = 'Daria tudo que sei pela metade do que ignoro'  ## Elemento iteravel que tem iteração por indice
tamanho_frase = len(frase)  ## Usando o len para pegar a quantidade de indices dentro da string
contador = 0

#while contador < tamanho_frase:  ## O laço vai pegar o contador e exibi-lo pela quantidade de indices
#    print(frase[contador], contador) ## O contador vai pegar cada indice da frase e exibir ao lado o valor do contador apresentando cada valor em seu indice
#    contador += 1


# Usando condições 
nova_string = '' ## Vamos adicionar valores a essa nova string

while contador < tamanho_frase:
    letra = frase[contador] ## A variavel assume cada indice da string
    print(nova_string)
    nova_string += letra ## Adiciona o valor na nova string usando cada valor pela variavel letra
    contador += 1

while contador < tamanho_frase:
    letra = frase[contador] ## A variavel assume cada indice da string
    if letra == 'e':  ## Se a letra for igual a 'e' inicia a condição
        nova_string += 'E' ## A string vai receber o valor alterado de 'e' para 'E'
    else:
        nova_string += letra
    contador += 1

while contador < tamanho_frase:
    letra = frase[contador] ## A variavel assume cada indice da string
    nova_string += letra.upper() ## O uso do UPPER converte o valor de cada letra para maiusculo 
    contador += 1

print(nova_string)

DARIA TUDO QUE SEI PELA METADE DO QUE IGNORO


In [ ]:
'''ESTRUTURA DE REPETIÇÃO FOR'''

# O uso do FOR é bem mais pratico e simples que o WHILE

texto = 'Python'

for i in texto:  ## Para cada indice no texto a condição será exibida 
    print(i.upper()) ## Usando com o UPPER

# Usando o contador para verificar o indice

for n, i in enumerate(texto): ## Usando o ENUMERATE ele retorna um contado baseando-se no indice da variavel
    print(n, i) ## Exibe o valor e o indice

# Usando função RANGE

for n in range(10): ## (inicio, fim, passo)
    print(n)

P
Y
T
H
O
N
0 P
1 y
2 t
3 h
4 o
5 n
0
1
2
3
4
5
6
7
8
9


In [26]:
'''LISTA - Usado para armazenamento de dados na qual tem interação com os indices sendo diferente de strings ou variaveis'''

#Indice   0    1    2    3    4
lista = ['Espanador','Van','Chupeta','Forte','Almofada','Fervura','Cereja','Sete','Trepadeira','Agricultor'] ## Uma variavel recebe um quantidade de valores de forma separada contato os indices de forma iteravel

print(lista[2]) ## Exibirá somente o valor que estiver alocado no indice 2
print(lista[0::2])  ## Usando Fatiamento de lista acessando pelos indices [ínicio:fim:passo]

# append, insert, Del, pop, clear, extend, min, max - Todos pode ser usado o fatiamento

lista2 = [ '13','20','65','96','71','46','67','74','60','67','41','75','44','26']

## APPEND - Insere um valor ao fim da lista
print(lista2) ## Exibirá os valores contidos na lista2 
lista2.append(25)  ## O append insere um valor no fim da lista 
print(lista2) ## I´ra exibir os valores após inser o valor com o append

##INSERT - Insere um valor no indice desejado
lista2.insert(0, 'banana') ## Inseriu o valor banana no indice 0 da lista
print(lista2)

##DEL - Deleta um valor específico da lista a partir do indice desejado
del(lista2[0]) ## Deleta o valor no indice 0
print(lista2)

##POP - Deleta o ultimo valor da lista
lista2.pop() ## O POP deleta o ultimo valor inserido na lista
print(lista2)

##EXTEND - Usado para unificar varias listas
lista3 = ['Arroz', 'Cebola']
lista3.extend(lista)
print(lista3)

##CLEAR - Limpa todos os valores da lista
lista3.clear() ## O Clear vai apagar todos os valores da lista3
print(lista3)

##MIN - Retorna o valor minimo da lista
print(min(lista2))

##MAX - Retorna o maior valor da lista
print(max(lista2))

##RANGE/LIST - Pode ser  usado a função range associado com a funçao list para gerar elementos de uma lista numerica.
lista4 = range(0,100,6) ## Usando o fatieamento para criar a lista
print(lista4) ## Será exibido a o range apenas sem ter os elementos na lista para isso é simples
lista4 = list(range(0,100,6)) ## Usando a função list sera gerado uma lista a partir da função range
print(lista4)


Chupeta
['Espanador', 'Chupeta', 'Almofada', 'Cereja', 'Trepadeira']
['13', '20', '65', '96', '71', '46', '67', '74', '60', '67', '41', '75', '44', '26']
['13', '20', '65', '96', '71', '46', '67', '74', '60', '67', '41', '75', '44', '26', 25]
['banana', '13', '20', '65', '96', '71', '46', '67', '74', '60', '67', '41', '75', '44', '26', 25]
['13', '20', '65', '96', '71', '46', '67', '74', '60', '67', '41', '75', '44', '26', 25]
['13', '20', '65', '96', '71', '46', '67', '74', '60', '67', '41', '75', '44', '26']
['Arroz', 'Cebola', 'Espanador', 'Van', 'Chupeta', 'Forte', 'Almofada', 'Fervura', 'Cereja', 'Sete', 'Trepadeira', 'Agricultor']
[]
13
96
range(0, 100, 6)
[0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96]


In [ ]:
'''JOGO DA FORCA'''

palavra = 'papagaio'
letras_dig = []
chances = 3

while True:
    if chances <= 0:
        print('Você perdeu!!!')
        break

    letra = input('Digite uma letra: ')

    if len(letra) > 1:
        print('Ahhh esta errado, uma letra de cada vez!!!')
        continue
    
    letras_dig.append(letra)

    if letra in palavra:
        print(f'UHHUUU!!! A letra {letra}, existe na palavra secreta!!!')
    else:
        print(f'Poxaaa!!! A letra {letra}, existe não palavra secreta!!!')
        letras_dig.pop()
    
    palavra_temporaria = ''
    for letra_secreta in palavra:
        if letra_secreta in letras_dig:
            palavra_temporaria += letra_secreta
        else:
            palavra_temporaria += '*'

    if palavra_temporaria == palavra:
        print(f'Que legal, VOC~E GANHOU!!! A palavra era {palavra_temporaria}.')
        break
    else:
        print(f'A palavra secreta está assim: {palavra_temporaria}')

    if letra not in palavra:
        chances -= 1

    print(f'Você ainda tem {chances} chances')
    print()
    


In [56]:
'''FOR/ELSE - O uso do ELSE é somente em casos especiais'''

variavel = ['Marcos', 'Luiz', 'Pedro', 'Maria', 'Lucia']
## Varificando pelo laço for se à palavras iniciando por alguma condição

letra_verificar = input('Digite a letra a verificar: ')

for valor in variavel: ## Cria um laço para verificação
    if valor.lower().startswith(letra_verificar): ## Função verificar se o palavra inicia com a letra sendo minuscula ou maiuscula
        print(f'Existe uma palavra que começa com {letra_verificar}: {valor}')
    continue

Digite a letra a verificar: o


In [11]:
'''SPLIT, JOIN, ENUMERATE'''

#SPLIT 
string = 'Imagine uma nova história para sua vida e acredite nela' ## Variavel

lista = string.split(' ')  ## A função Split separa a variavel em uma lista a partir do separador utilizado sendo virgula, espaço ou outros
print(lista)  ## Retorna uma lista separada por espaço

#JOIN - Ajunta os valores de uma lista
lista2 = ' '.join(lista)  # A função Join ela pega os valores de uma lista e retorna uma string
print(lista2)

#ENUMERATE - Usado para numerar um laço 
for indice, valor in enumerate(lista):  #Usando o ENUMERATE ele ira retorno o valor no laço com o indice de cada palavra
    print(indice, valor)


['Imagine', 'uma', 'nova', 'história', 'para', 'sua', 'vida', 'e', 'acredite', 'nela']
Imagine uma nova história para sua vida e acredite nela
0 Imagine
1 uma
2 nova
3 história
4 para
5 sua
6 vida
7 e
8 acredite
9 nela


In [9]:
'''DESEMPACOTAMENTO DE LISTAS'''
# O desempacotamento de lista é simples a partir da quantidade de valores dentro da lista à necessidade do 
# mesmo valores em variaveis. ex

lista = [1,2,3]  ## Dado os valores a lista
l1, l2, l3 = lista  ## desempacotando os valores da lista em suas variaveis, repare que a quantidade é a msm
print(l2)  # Exibirá o valor da variavel l2

# Há uma diferença a partir da lista que tem um valor muito grande e não tem a necessidade de todos os 
# valores então usamos o *_ ou * com o nome da variavel desejada, ele irá recolher todos os valores restante
# ou inicial de uma lista. Ex

lista2 = ['Imagine', 'uma', 'nova', 'história', 'para', 'sua', 'vida', 'e', 'acredite', 'nela']
l1, l2, l3, *outros_valores = lista2  ## usando o '*' os outros valores seram alocados nessa variavel
## Ao imprimir os valores poderá ver os valores em cada variavel, pode usar dessa forma no inicio ou fim da lista
print(l1)
print(l2)
print(l3)
print(*outros_valores)

2
Imagine
uma
nova
história para sua vida e acredite nela


In [18]:
'''OPERADORES TERNARIOS EM PYTHON'''
# O uso de operadores ternarios facilita e simplificar a forma de trazer um resultado imediado com um codigo limpo
# Usando operadores ternarios em verificação de usuario logado no sistema. Ex1 sem operadores
usuario_logado = False  ## Dada as condições de login sendo falsa
if usuario_logado == True:  ## Se o usuario for verdadeiro exibirá
    print('Usuario logado')
else:  ## Se o for falso exibirá 
    print('Usuario não logado')
    
# Usando os operadores ternario 
logged_user = True ## Dada as condições de login sendo verdadeira
msg = 'Usuario logado' if logged_user else 'Usuario não logado'  ## A variavel msg ja tras as condições 
# com ela se a variavel for verdadeira ja exibirá a mensagem

print(msg)

# Teste em usuario e senha

user = input('Usuario: ')  ## Dada entrada do usuario e senha 
senha = input('Senha: ')

cad_senha = (len(senha) >= 8)  # Criamos a condição na qual a nova variavel irá verificar se o 
# tamanho da senha em maior ou igual a 8 digitos

msg2 = 'Logado' if cad_senha else 'Senha invalida'  # A variavel msg retornar logado caso a condição seja verdadeira
print(msg2)


Usuario não logado
Usuario logado
Usuario: wendell
Senha: 94563381
Logado


In [47]:
'''DESAFIO DOS CONTADORES - Retornar uma sequência de números proposto na aula'''

for i, n in enumerate(range(10, 1, -1)):
    print(i, n)

0 10
1 9
2 8
3 7
4 6
5 5
6 4
7 3
8 2


In [3]:
'''VALIDADOR DE CPF'''

cpf = input('Digite seu CPF: ')
novo_cpf = cpf[:-2]
total = 0
reverso = 10

for index in range(19):
        if index > 8:                   # Primeiro índice vai de 0 a 9,
            index -= 9                  # São os 9 primeiros digitos do CPF

        total += int(novo_cpf[index]) * reverso  # Valor total da multiplicação

        reverso -= 1                    # Decrementa o contador reverso
        if reverso < 2:
            reverso = 11
            d = 11 - (total % 11)

            if d > 9:                   # Se o digito for > que 9 o valor é 0
                d = 0
            total = 0                   # Zera o total
            novo_cpf += str(d) 
        
if novo_cpf == cpf:
    print('CPF valido')
else:
    print('CPF invalid')

CPF valido


In [ ]:
'''TUPLAS'''
# Tuplas são utilizadas para armazenamento de dados assim como as listas com uma diferença as tuplas
# são objetos imutaveis que não mudam seus valores. EX

tupla = (1, 2, 3, 4, 'banana')
print(tupla)

# Sendo um valor imutavel não tem funções built-in para uso nas tuplas, mais uma tupla pode se tornar uma lista

lista = list(tupla)

print(lista)

# As tuplas aceitam fatiamentos,criação de lista dentro delas e outros mesmo sendo imutavel.

print(tupla[2])  # Seleção por indice
print(tupla[::-1])  # Fatiamento


'''DICIONARIOS'''
# Os dicionarios são utilizados para armazena dados imutaveis porem a diferença é que eles nao alocam objetos e sim valores e sua forma é baseada em keys no caso chave e valor. EX

dicionario = {'nome':'Wendell', 'sobrenome':'Barcelos', 'idade':30}

'''SETS'''

In [32]:
'''FUNCTIONS - FUNÇÕES EM PYTHON'''
# A palavra reservada def inicia a definição de uma função. Ela deve ser seguida do nome da função e da 
# lista de parâmentro entre parenteses. EX.
def hello_world(nome):  # Definindo a função
    texto = f'Olá {nome}! Prazer em te conhecer.'  # A função retornará o texto com o parametro inserido
    print(texto)

hello_world('Maria')  # Chamando a função e passando parametro retornará o valor de dentro da função

lt = []

def add_lista(x):
    for i in x:
        lt.append(i)

add_lista('We re still in the process of editing this introduction')
print(lt)

# Criando uma função que vai desempacotar usando FOR para retornar o valor 

def desempacote(palavra):  # Definindo a função
    for x in palavra:  # Passando a estruturura For e retornando os valores
    print(x)
        
desempacote("paralelepipedo")  #  Usando uma string simples
# A função se torna muito poderosa para grandes retornos temos o exemplo com uma lista
lista = ['Imagine', 'uma', 'nova', 'história', 'para', 'sua', 'vida', 'e', 'acredite', 'nela']  
desempacote(lista)  # Retorna todos os valores da lista

'''Nomeando parametros''' 
# Em alguns momento a função já vai vir com os paremetros nomeados quer dizer que ja tem um valor alocado ao
# determinado parametro mais ele pode ser substituido por outro valor.

def valores(nome, sob_nome='Barcelos'):  # Criando os parametros sendo um de entrada e outro alocado
    print(f'Olá {nome} {sob_nome}, tudo bem?')  # Exibirá os valores 

valores('Wendell')  # Retornará os dois valores porem com uma entrada
valores('Wendell', 'Pestana')  # Também podemos mudar os valores quando o parametro vem alocado retornar o valor de entrada
 
'''Args, Kwargs'''
# Args são parametros direcionados a uma lista com valores indefinidos, com varias entradas
# Kwargs são parametros direcionados a um dicionario com valores indefinidos, com varias entradas

def lojinha(modelo, *args, **kwargs):  # Passando os paramentros simples, args e kwargs
    print(f'Você escolheu o modelo: {modelo}')  # Retorna o valor simples
    print('-' * 50)
    
    for arg in args:  # Usando for para retornar todos os valores alocados na lista
        print(arg)
    print('-' * 50)
    
    for kw in kwargs:  # Usando for para retornar todos os valores alocados no dicionario
        print(kw, ':', kwargs[kw])
        
        
lojinha('Tenis Nike 4 Molas',                             # Entrada simples
        'Preto', 'Azul', 'Cinza', 'Branco', 'Amarelho',   # Usando varios valores no args
        tipo='Nike Air', cor='Preto/Branco', tamanho=42)  # Usando varios valores no Kwargs

'''Argumentos Posicionais e nomeados'''
# def nome_função(p1, p2, /, p_or_kwd, *, kw1, kw2)
#                   |          |                |
#                   |   Posicional ou Chaveado  | 
#            Posicional apenas                  |
#                                        Chaveado apenas

# Argumentos posicional-ou-nomeados: Se / e * não estão presentes na definição da função, argumentos podem ser passados para uma função por posição ou por nome.
# Parâmetros somente-posicionais: Olhando com um pouco mais de detalhes, é possível definir certos parâmetros como somente-posicional. Se somente-posicional, a ordem do parâmetro importa, 
# e os parâmetros não podem ser passados por nome. Parâmetros somente-posicional são colocados antes de / (barra). A / é usada para logicamente separar os argumentos somente-posicional dos demais parâmetros. 
# Se não existe uma / na definição da função, não existe parâmetros somente-posicionais.
# Parâmetros após a / podem ser posicional-ou-nomeado ou somente-nomeado.
# Argumentos somente-nomeados: Para definir parâmetros como somente-nomeado, indicando que o parâmetro deve ser passado por argumento nomeado, 
# colocamos um * na lista de argumentos imediatamente antes do primeiro parâmetro somente-nomeado.

def funcao_normal(arg):  # Criando uma função normal com um retorno simples
    print(arg)
    
def posicional(arg, /):  # Criando uma função posicional 
    print(arg)
    
def chaveado(*, arg):  # Criando uma função chaveado
    print(arg)
    
def chaveado(pos, /, normal, *, chave):  # Criando uma função combinando todas
    print(pos, normal, chave)
    

funcao_normal(1)  # O retorno será normal a partir das entradas de forma simples
funcao_normal(arg=5)

posicional(1)  # O retorno será normal porem no segundo exemplo terá um erro aonde passando o parametro ele 
posicional(arg=5)  # não aceitará o valor por conta da posição

chaveado(arg=1)  # Retornará o argumento porem não o valor posicional somente o primeiro aparecerá
chaveado(1)

chaveado(1, normal=5, chave='Wendell')  # O retorno será a combinação

'''Função Lambda'''
# Uma forma muito usada dentro do analise da dados com Pandas e Numpy é as funções Lambdas, uma sintaxe simples
# e objetiva de trazer retorno diminuindo o tamanho da função, muito usada com estruturas de controle.

def increment(x):  # temos uma função de incremento na qual recebe um valor e soma mais 1
    return x + 1  # Retorna o valor + 1

increment(1)  # Temos a entrada do valor 1 sendo somado a 1 retornando 2

# Podemos ver a mesma função usando o Lambda 
increment = lambda n: n + 1  # Com o lambda podemos ter o mesmo resultado de forma simples
increment(5)  # O retorno será a soma de 5 + 1

    

IndentationError: expected an indented block (<ipython-input-32-d50cc60bc962>, line 23)

In [2]:
# EXERCICIOS FUNÇÕES -> https://wiki.python.org.br/ExerciciosFuncoes

In [15]:
'''Ex1. Crie uma função que receba 2 números. O primeiro número é um valor e o segundo um percentual.
Retorne o valor do primeiro número somado do aumento do percentual do mesmo'''

def soma_percent(val, porc):  # A 
    porc = porc / 100
    return val + (val * porc)

soma_percent(100, 80)

180.0

In [17]:
'''Ex2. Faça um programa, com uma função que necessite de três argumentos, e que forneça a soma desses 
três argumentos. '''

def soma_de_num(n1, n2, n3):
    return n1 + n2 + n3

soma_de_num(5, 8, 9)

22

In [22]:
'''Ex3. Faça um programa, com uma função que necessite de um argumento. A função retorna o valor de caractere 
‘P’, se seu argumento for positivo, e ‘N’, se seu argumento for zero ou negativo. '''

def neg_pos(x):
    if x > 0:
        return 'Positivo'
    else:
        return 'Negativo'
    
neg_pos(20)

'Positivo'

In [ ]:
'''Ex4. Faça um programa com uma função chamada somaImposto. A função possui dois parâmetros formais: 
taxaImposto, que é a quantia de imposto sobre vendas expressa em porcentagem e custo, que é o custo de 
um item antes do imposto. A função “altera” o valor de custo para incluir o imposto sobre vendas. '''

def somaImposto(custo, taxaImposto):
    porc = taxaImposto / 100
    return f'Valor de Custo: {custo} | Taxa de Imposto: {taxaImposto}% | Valor a Pagar: {custo + (custo * porc)}'
        

somaImposto(1500, 10)

In [ ]:
'''Ex5. Faça um programa que use a função valorPagamento para determinar o valor a ser pago por uma 
prestação de uma conta. O programa deverá solicitar ao usuário o valor da prestação e o número de dias 
em atraso e passar estes valores para a função valorPagamento, que calculará o valor a ser pago e 
devolverá este valor ao programa que a chamou. O programa deverá então exibir o valor a ser pago na tela. 
Após a execução o programa deverá voltar a pedir outro valor de prestação e assim continuar até que seja 
informado um valor igual a zero para a prestação. Neste momento o programa deverá ser encerrado, exibindo 
o relatório do dia, que conterá a quantidade e o valor total de prestações pagas no dia. O cálculo do 
valor a ser pago é feito da seguinte forma. Para pagamentos sem atraso, cobrar o valor da prestação. 
Quando houver atraso, cobrar 3% de multa, mais 0,1% de juros por dia de atraso.  '''

def valorPagamento(valor, atraso):
    multa = valor + (valor * 0.03)
    val = valor + (multa * (atraso * 0.01))
    return val

#while True:
    x = int(input('Valor a Pagar: '))
    y = int(input('Atraso em dias: '))
    if x <= 0:
        break
    valorPagamento(x, y)

In [30]:
'''Manipulação de Arquivos'''
# Com o python existe algumas formas de manipular arquivos existentes ou até mesmo criar arquivos, apagar e reescrever

# df = open('arquivo.txt', 'w')  # Nesse momento o python criou um arquivo de texto para escrita, porem ele subescreve o arquivo
# df.close()  # Para finalizar o arquivo
# # A partir desse arquivo podemos ler, escrever, adicionar, subescrever
# df = open('arquivo.txt', 'r')  # O read ler o arquivo
# df.close()
# df = open('arquivo.txt', 'a')  # O append vai escrever sem apagar ou subescrever o que tem no arquivo
# df.close()
# df = open('arquivo.txt', 'r+')  # O read plus ele vai ler e escrever
# df.close()

# Para não ter nenhum problema de perda de dados usamos uma função WITH
# with open('arquivo.txt') as df:  # É passado para a função abrir e colocar os arquivos na variavel df
#     dados = df.read()  # Criado mais uma variavel para leitura dos dados 
# print(dados)  # Exibe os valores da variavel 
# print(df.closed)  # E retorna se a variavel df foi fechada após rodar a função

# # Após fechar um arquivo ele não consegue ler precisa abrir novamente
# df = open('arquivo.txt')
# df.close()
# df.read()  # Apos fechar o arquivo precisa abrir novamente para leitura senão ele dar erro e nao ler

# Adicionando valor no arquivo usando o with
with open('arquivo.txt','a') as df:
    f = 'Marcelo (48.522)'
    print(df.write(f))
    df.close()
    
d = open('arquivo.txt','r')
d.read()
df.close()    

16


In [28]:
df

<_io.TextIOWrapper name='arquivo.txt' mode='a' encoding='cp1252'>

In [ ]:
'''Funções - *args **kwargs'''
# Criar uma função que recebe os valores em kwargs mais só exibe se todos os valores estiverem inseridos
def func(*args, **kwargs):
    print(args)

    nome = kwargs.get('nome')  # A função get vai buscar dentro dos valores de kwargs se a chave nome foi inserido e retornará na variavel

    if nome is not None:  # Se nome não for NONE ele exibirá os valores senão exibirá uma frase.
        print(kwargs)
    else:
        print('Insira todos os dados')

In [ ]:
func(145, 51, sobrenome='barcelos', idade=30)

In [29]:
'''EX1 - Crie uma função que recebe uma função2 como parametro e retorne o valor da função2 executada'''

def func():  # A primeira função a qual vai retornar não terá parametro 
    return 'Hello world'

def func2(funcao):  # A função 2 vai receber um parametro porem o retorno dela será a função 1 na qual vai receber o valor de retorno da func1
    return funcao()

exec = func2(func)  # Alocando a função 1 como parametro da func 1 
print(exec)

In [ ]:
'''Expressões Lambda'''
# Vamos pegar um exemplo para ordenar uma lista

lista = [
         ['P1', 13],
         ['P2', 6],
         ['P3', 7],
         ['P4', 50],
         ['P5', 8],
]

def func(item):  # Criamos uma função para retornar o item alocado no indice 1
    return item[1]

lista.sort(key=func)  # Usando a funçao sort para ordenar a lista passamos que a ordenação será pela chave da função
print(lista)          # Se quiser a ordem do maior para o menor use a função reverse=True

# Usando lambda

lista.sort(key=lambda item: item[1])  # Simplificando a função com lambda 
print(lista)

# Outra forma 
print(sorted(lista, key=lambda i: i[1]))  # Vai fazer da msm forma sendo ainda mais simplificada

# Outra forma de uso do lambda

soma = lambda x, y: x + y  # Chamamos a expressão e os parametros com o retorno
print(soma(5, 2))


In [ ]:
'''List Comprehension'''
# Compreensão de listas é a forma mais simples de interar em uma lista simplificando o uso de estruturas

l1 = [1,2,3,4,5,6,7,8,9]  # Temos uma lista e precisamos multiplicar todos os valores dessa lista
l2 = []  # E criamos uma lista vazia para colocar todos os valores multiplicados por 2

for i in l1:  # Usando o FOR para passar por todos os valores
    v = i * 2  # Temos o v recebendo cada item e multiplicando por 2
    l2.append(v)  # Usando a função apppend ele envia para lista vazia todos os valores gerando a l2
print(l2)  # Retorna o valor da lista

# Sendo uma estrutura bem maior do que se usar as list comprehensions, vejamos

l3 = [v * 2 for v in l1]  # Usando uma forma mais simples aonde o [valor * 2 para valor em l1]
print(l3)  # Retorna a mesma lista porem de forma simplificada


l4 = ['Laura', 'Mauro', 'Marcelo']  # Usando uma lista de string
ex = [v.replace('a', '@').upper() for v in l4]  # Passamos a função replace para substituir o 'a' por '@' e o upper para colocar tudo em maiusculo
print(ex) 

# Usando IF

l5 = list(range(100))  # Criamos uma lista com o tamanho de 100 numeros
ex2 = [v for v in l5 if v % 6 == 0]  # Na variavel irá alocar todos os valores que dividido por 6 é igual a 0
print(ex2)

ex3 = [v for v in l5 if v % 5 == 0 if v % 6 == 0]# Na variavel irá alocar todos os valores que dividido por 5 e por 6 que é igual a 0
print(ex3)


In [ ]:
'''ZIP e ZIP_LONGEST - Unindo iteráveis'''
# Supondo que temos uma quantidade de codigo e duas listas de cidades e estados na qual precisamos agrupar esses dados

cidades = ['São Paulo', 'Belo Horizonte', 'Salvador', 'Bangu']

estados = ['SP', 'MG', 'BA', 'RJ']

estados_cidades = zip(estados, cidades)  # Ao criar uma lista usando o zip ele retorna um gerador na qual é necessario transformar em lista ou usar o for para retorno dos dados
print(estados_cidades)  # Retorna o valor em memoria

print(list(estados_cidades))  # Transformando em lista os valores retornaram 

for v in estados_cidades:  # Usando for para desempacotar 
    print(v)

# A diferença do zip para o zip_longest é que o zip cria uma lista com os menos valores já a zip_longest usa todos os valores porem usa o NONE para valores que nao tem chave
# O zip_longest é necessario importar o modulo itertools - from itertools import zip_longest

from itertools import zip_longest, count  # importando os modulos

indice = count()  # O modulo Count gera um contador
# Usando as listas acima estados e cidades vamos desempacotar usando zip pois o zip_longest pode gerar algo muito grande e travar o notebook

cidades_estados =  zip(indice, estados, cidades)  # Criando o gerador atraves do zip 

for indice, estado, cidade in cidades_estados:  # O for vai desempacotar os valores, uma otima forma para numera os valores com Count
    print(indice, estado, cidade)


In [ ]:
'''
Considerando duas listas de inteiros ou float (lista A e lista B). Some os valores nas listas retornando uma nova lista com os valores somados:
Se uma lista for maiors que a outra, a soma só vai considerar o tamanho da lista menor.'''

lista_a = [1,3,5,7,9,11,13,15,17,19]
lista_b = [2,4,6,8,10,12,14,16,18,20]

# 1ª forma
lista_soma = []  

for i in range(len(lista_a)): # Usando o range e o len para pegar o tamanho pelos indices
    lista_soma.append(lista_a[i] + lista_b[i])  # O append vai colocar cada valor na lista vazia pegando a soma pelos indices

print(lista_soma)

# 2ª forma usando list comprehensions - Forma mais pythonica
lista_soma2 = [x + y for x, y in zip(lista_a, lista_b)]
print(lista_soma2)


In [ ]:
'''COUNT - Contadores'''

from itertools import count
contador = count(start=2, step=2)

for c in contador:
    print(c)
    if c >= 10:
        break

# Adicionando indices com o contador

cont = count()  #Criando um contador para trazer os indices da lista
lista_nomes = ['Luiz', 'João', 'Maria', 'José', 'Silva', 'Eduardo']  # Com uma lista de nome 

lista = zip(cont, lista_nomes)  # Criando uma lista e usando o zip para pegar o contador e os valores da outra lista

print(list(lista))  # O retorno dos valores será criando uma lista e exibindo os valores


In [1]:
'''GROUPBY -  Agrupamento de dados'''

from itertools import groupby

alunos = [
    {'nome': 'Luiz', 'nota': 'A'},
    {'nome': 'Leticia', 'nota': 'B'},
    {'nome': 'Fabricio', 'nota': 'A'},
    {'nome': 'Rose', 'nota': 'C'},
    {'nome': 'Joana', 'nota': 'D'},
    {'nome': 'João', 'nota': 'A'},
    {'nome': 'Eduardo', 'nota': 'B'},
    {'nome': 'Andre', 'nota': 'A'},
    {'nome': 'Anderson', 'nota': 'C'},
    {'nome': 'José', 'nota': 'B'},
    {'nome': 'Cecilia', 'nota':'D'}
]
ordena = lambda item: item['nota']
alunos.sort(key=ordena)
alunos_agrupados = groupby(alunos, ordena)

for agrupamento, valores_agrupados in alunos_agrupados:
    print(f'Agrupamento: {agrupamento}')
    qtd = len(list(valores_agrupados))
    print(f'{qtd} alunos tiraram nota {agrupamento}')



Agrupamento: A
4 alunos tiraram nota A
Agrupamento: B
3 alunos tiraram nota B
Agrupamento: C
2 alunos tiraram nota C
Agrupamento: D
2 alunos tiraram nota D


In [2]:
"""MAP - Mapeamento de dados"""

produtos = [
    {'prod': 'Cadeira Poltrona', 'preco': 399},
    {'prod': 'Canto Alemão', 'preco': 84.50},
    {'prod': 'Rádio Antigo', 'preco': 278},
    {'prod': 'Geladeiras', 'preco': 1199},
    {'prod': 'TV', 'preco': 1599},
    {'prod': 'Perfumaria', 'preco': 59},
    {'prod': 'Cadeira Madeira', 'preco': 199},
    {'prod': 'Lustre Sala De Jantar', 'preco': 159},
    {'prod': 'TV Samsung', 'preco': 2199},
    {'prod': 'Kunai', 'preco': 99},
]

pessoas = [
    {'nome': 'Luiz', 'idade': 32},
    {'nome': 'Maria', 'idade': 26},
    {'nome': 'Jorge', 'idade': 60},
    {'nome': 'Lucas', 'idade': 18},
    {'nome': 'Ingrid', 'idade': 12},
    {'nome': 'Lorenzo', 'idade': 42},
    {'nome': 'Marcus', 'idade': 33},
    {'nome': 'Pedro', 'idade': 58},
    {'nome': 'Augusto', 'idade': 22},
    {'nome': 'Marlon', 'idade': 37},
]

# Usando a lista produtos é necessario alterar os valores do preço com desconto e para isso o MAP vai ser a solução
# Vamos definir uma função para fazer a alteração de valores

#print(produtos[0])
#print()

def aumenta_preco(p):
    p['preco'] = round(p['preco'] * 1.05, 2)  # Função pega o parametro com o indice preco e atribui o valor da porcentagem multiplicado a preco
    return p

novos_precos = list(map(aumenta_preco, produtos))  # O Map cria uma nova lista aonde ele vai substituir os valores dos produtos com base na função

#for produto in novos_precos:  # Usando um for para os valores retornarem de forma visivel
#    print(produto)


# Usando o MAP com lista de valores numericos

import numpy as np

lista = np.random.randint(50, size=10)  # Usando o random pelo numpy, a função randint informa o range dos valores até 50 e passando o tamanho da amostra sendo 10 valores

l3 = []

nova_lista = list(map(lambda x: x * 2, lista))  #Usando o map para mapear a lista e a função lambda vai pegar cada elemento e multiplicar por 2, convertendo em uma lista
l3.append([i * 2 for i in lista])  # Usando list Comprehensions para colocar a lista gerada em uma lista 


print(lista)
print(nova_lista)
print(l3)




[42 28 40 36 45 34 38 42 46 20]
[84, 56, 80, 72, 90, 68, 76, 84, 92, 40]
[[84, 56, 80, 72, 90, 68, 76, 84, 92, 40]]


In [3]:
import random  # Importando a função random para trazer valores aleatorios

# Usando a função sample passando o range de valores e o tamanho da amostra retornar uma lista de valores aleatorios com o tamanha de 10 indices
l4 = random.sample(range(1,100), k=25)

print(l4)

[19, 94, 9, 57, 13, 87, 21, 11, 72, 5, 17, 7, 96, 74, 84, 62, 66, 46, 25, 75, 48, 85, 51, 22, 81]


In [4]:
'''FILTER -  Filtragem de dados'''
# A função filter é bem parecida com a map, ela vai filtrar na lista respeitando a estrutura passada para ela

# Usando a lista random acima iremos buscar valores entre 20 a 35
filtro_lista = list(filter(lambda x: x > 20 and x < 59, l4))  # Usando o filter ele vai buscar dentro dos valores da lista random e retornar pela estrutura solicitada
filtro_l2 = [x for x in l4 if x % 3 == 0]  # Usando list Comprehensions a condição é retornar todos os valores multiplos de 3 onde resta 0

print(sorted(filtro_lista))  # Ordenando os valores retornados
print(filtro_l2)
print()

# Usando função para retorna a condição acima, o uso da função def é bom porque pode ser reutilizavel em outros locais

def filtrando(x):
    if x % 3 == 0:
        return True

div = list(filter(filtrando, l4))
print(div)
print()

# Buscando so produtos a partir do preço, usando a função lambda para passar a condição de retorno dos produtos. Obs: Otimo para buscar valores em dataframes
filtro_prods = filter(lambda x: x['preco'] > 50 and x['preco'] < 120, produtos)

for p in filtro_prods:
    print(p)

print()

# Usando função para retornar condições na qual pode ser usada outra vezes 
def filtrar(x):  # Criando a função de filtro
    if x['idade'] > 18 and x['idade'] < 29:  # Passando as condições usando o IF para e retornando verdadeiro
        return True

filt_idade = filter(filtrar, pessoas)  # O filtro recebe a função e a lista a filtrar

for p in filt_idade:
    print(p)


[21, 22, 25, 46, 48, 51, 57]
[9, 57, 87, 21, 72, 96, 84, 66, 75, 48, 51, 81]

[9, 57, 87, 21, 72, 96, 84, 66, 75, 48, 51, 81]

{'prod': 'Canto Alemão', 'preco': 88.73}
{'prod': 'Perfumaria', 'preco': 61.95}
{'prod': 'Kunai', 'preco': 103.95}

{'nome': 'Maria', 'idade': 26}
{'nome': 'Augusto', 'idade': 22}


In [5]:
import random  # Importando a função random para trazer valores aleatorios

# Usando a função sample passando o range de valores e o tamanho da amostra retornar uma lista de valores aleatorios com o tamanha de 10 indices
l4 = random.sample(range(1,100), k=25)

print(l4)

[69, 17, 45, 22, 97, 31, 18, 75, 11, 30, 55, 78, 51, 89, 13, 57, 77, 19, 4, 53, 21, 63, 34, 39, 48]


In [6]:
'''REDUCE - Acumuladora de valores''',
# A função Reduce acumula valores ela soma todos os valores vejamos
from functools import reduce  # necessario importar-lo

soma_lista = reduce(lambda ac, i: i + ac, l4, 0)  # A função reduce nesse caso vai receber dois parametros na qual cada item vai somar com o acumulador que se inicia com 0

l5 = []
l5.append(reduce(lambda ac, i: i + ac, l4, 0))  # Nesse momento todas as vezes que lista L4 gira ele soma todos os valores e adiciona na lista

print(soma_lista)
print(l5)

# Usando o reduce para obter a media de idade da lista acima

# No reduce a expressão fica reduce( lambda recebe 2 parametros item, acumulado: item soma com acumulador, lista, iniciando em valor)
media_reduce = reduce(lambda ac, i: ac + i['idade'], pessoas, 0)
# A ideia é retorna a soma de todos os valores para obter a media dividindo pelo tamanho da lista 
print(media_reduce / len(pessoas))


1116
[1116]
34.0


In [7]:
# Importando a biblioteca Numpy
import numpy as np

In [50]:
'''Array'''
# Arrays são objetos que armazenam estruturas sequencias de dados de tipo e tamanhos determinado que apontam
# para uma sequência de dados na memória RAM.

# Usando a biblioteca numpy vamos criar um array

array = np.array([1,2,3,4,5])

# A matriz é uma estrutura na qual é um array de array.
matriz = np.array([[1,2,3,4,5],[6,7,8,9,10]])

# Com o numpy existe diversas formas de trabalhar com os arrays
# Dados isso é fácil perceber que um array tem as seguintes características que podem ser acessadas na forma de atributos deste objeto:

   # dtype: O tipo de dados do array
   # shape: O tamanho do array em linhas e colunas
   # size: O tamanho do array em quantidade de elementos
   # itemsize: O consumo de memória de cada elemento do array (em bytes)
   # strides: Uma distancia em bytes entre os elementos armazenados na memória

print(
    f"array: dtype={array.dtype} | shape={array.shape}| size={array.size} "
    f"| itemsize={array.itemsize} | strides={array.strides}"
)

print(
    f"matriz: dtype={matriz.dtype} | shape={matriz.shape} | size={matriz.size} "
    f"| itemsize={matriz.itemsize} | strides={matriz.strides}"
)
print()
# Dado que inicializações de diferentes tipos de array são bastante comuns, a biblioteca contém uma série 
# de funcionalidades que permitem criar arrays com diferentes tipos de dados
# np.zeros -> Cria um array preenchido com zeros
print(f'Zeros: {np.zeros(shape=(3,2))}')
# np.ones -> Cria um array preenchido com um's
print(f'Ones: {np.ones(shape=(3,2))}')
# np.eye -> Cria a matriz identidade com o tamanho específicado
print(f'Eye: {np.eye(4)}')
# np.arange -> Mesma coisa que a função range, só que para arrays
print(f'Arange: {np.arange(1,20,2)}')
# np.linspace -> Cria um array entre dois números espaçados linearmente
print(f'Linspace: {np.linspace(5,11, num=5)}')
# np.logspace -> Cria um array entre dois números espaçados logaritimicamente
print(f'Logspace: {np.logspace(0, 1, 3)}')
# np.random.int -> Cria um array de valores aleatóries entre um valor menor e maior (exclusivo)
print(f'Random Int: {np.random.randint(1,100,size=10)}')
# np.random.normal -> Cria um array aleatório com valores baseados em uma distribuição normal
print(f'Random Normal: {np.random.normal(1,2,10)}') 


array: dtype=int32 | shape=(5,)| size=5 | itemsize=4 | strides=(4,)
matriz: dtype=int32 | shape=(2, 5) | size=10 | itemsize=4 | strides=(20, 4)

Zeros: [[0. 0.]
 [0. 0.]
 [0. 0.]]
Ones: [[1. 1.]
 [1. 1.]
 [1. 1.]]
Eye: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Arange: [ 1  3  5  7  9 11 13 15 17 19]
Linspace: [ 5.   6.5  8.   9.5 11. ]
Logspace: [ 1.          3.16227766 10.        ]
Random Int: [20  6 48 34 61 28 34 64 24 14]
Random Normal: [ 1.07825829  1.86407201  5.22085972  0.91600732  1.89630316 -1.039282
 -1.15955569  3.75433071 -0.39486885  1.82796738]


In [62]:
'''Gere uma matriz 4x4 de números igualmente espaçados entre 5 e 11 e calcule o total de memória utilizado 
para armazenar este array'''
ex = np.linspace(5,11,num=16).reshape(4,4)
print(ex)
print(f'Bytes: {ex.size * ex.itemsize}')

[[ 5.   5.4  5.8  6.2]
 [ 6.6  7.   7.4  7.8]
 [ 8.2  8.6  9.   9.4]
 [ 9.8 10.2 10.6 11. ]]
Bytes: 128


In [2]:
# Importar biblioteca
import numpy as np

#RANDOM SEED
#np.random.seed() - dada a função random seed ela semeia um valor randomico na raiz da memoria onde em todas
# as vezes que o valor da raiz for chamado ele retorna os mesmo valores mesmo usando outra variavel. EX:

np.random.seed(30)  # Valor da raiz 30
arr3 = np.random.randint(1,100,10)  # Criando um array de valores randomicos
print(arr3)  # Retorno dos valores

np.random.seed(30)  # Usando o valor da raiz 30 novamente
arr4 = np.random.randint(1,100,10)  # Criando outro array de valores randomicos
print(arr4)  # Retorno dos valores

# Os valores que iram retornar seram os mesmo pois esta usando a função seed com o valor da raiz

[38 38 46 46 13 24  3 54 18 47]
[38 38 46 46 13 24  3 54 18 47]


In [11]:
''' Funções Numpy de agregação - mais recorrentes

np.mean: Calcula a média
np.median: Calcula a mediana
np.min: Calcula o valor mínimo
np.max: Calcula o valor máximo
np.std: Calcula o desvio-padrão
np.var: Calcula a variância
np.percentile: Calcula o percentil específicado
np.sum: Calcula a soma de todos os elementos
np.count_nonzero: Realiza a contagem dos elementos não nulos do array
np.unique: Obtém os valores únicos de um array '''

np.random.seed(42)
A = np.random.normal(loc=5, size=(5, 3))
B = np.random.choice(["A", "B", "C"], size=(5, 3))
C = np.array([0, 1, 2, 0, 4, 5])
D = np.random.normal(size=(5, 3))


In [20]:
np.mean(D)

0.11177418874303463

Faça um programa que leia um número indeterminado de valores, correspondentes a notas, encerrando a entrada de dados quando for informado um valor igual a -1 (que não deve ser armazenado).

Após esta entrada de dados, faça:

    1. Mostre a quantidade de valores que foram lidos;
    2. Exiba todos os valores na ordem em que foram informados;
    3. Exiba todos os valores na ordem inversa à que foram informados;
    4. Calcule e mostre a soma dos valores;
    5. Calcule e mostre a média dos valores;
    6. Calcule e mostre a quantidade de valores acima da média calculada;
    7. Calcule e mostre a quantidade de valores abaixo de sete;
    8. Encerre o programa com uma mensagem;




In [2]:
import numpy as np
import pandas as pd

In [3]:
### Series (Pandas)
# EX: Represente o gráfico abaixo como uma série, na qual os paises são os indices e os casos são os dados.

paises = ['Belgium','Israel','Czechia', 'Panama', 'Kuwait', 'United State', 'Peru', 'Chile', 'Argentina', 'Spain']
dados = [39166, 35572, 33103, 32300, 30957, 28414, 28213, 27455, 26593, 26554]

serie = pd.Series(data=dados, index=paises, name='Dados Covid')
serie

Belgium         39166
Israel          35572
Czechia         33103
Panama          32300
Kuwait          30957
United State    28414
Peru            28213
Chile           27455
Argentina       26593
Spain           26554
Name: Dados Covid, dtype: int64

In [4]:
'''EX: Abaixo carregamos uma série de dados com o número de casos de COVID registrados por país na data mais
recente. Cada país é representadado por um código ISO de 3 letras, entretanto, dentro dessa série há alguns 
códigos que começam com "OWID_", que representam grupos de países não oficiais. Por exemplo, "OWID_AFR" 
representa todos os países da áfrica. Para os países que começam com "OWID_" troque o valor registrado por np.nan'''

serie_owid = pd.read_csv(
    "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/latest/owid-covid-latest.csv"
).set_index("iso_code")["total_cases"]

novo = [x for x in serie_owid.index if x.startswith('OWID_')]
serie_owid[novo] = np.nan
serie_owid
        

iso_code
AFG         180688.0
OWID_AFR         NaN
ALB         276415.0
DZA         265900.0
AND          43067.0
              ...   
WLF            454.0
OWID_WRL         NaN
YEM          11822.0
ZMB         322207.0
ZWE         253508.0
Name: total_cases, Length: 234, dtype: float64

In [5]:
### Ex: Calcule a distância euclidiana entre duas séries

p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

(p - q).dot(p - q) ** 0.5

18.16590212458495

In [6]:
np.random.seed(42)
A = np.random.normal(loc=5, size=(5,5))
print(A, np.round(A, 2))  # Arredondamento de valores no array

[[5.49671415 4.8617357  5.64768854 6.52302986 4.76584663]
 [4.76586304 6.57921282 5.76743473 4.53052561 5.54256004]
 [4.53658231 4.53427025 5.24196227 3.08671976 3.27508217]
 [4.43771247 3.98716888 5.31424733 4.09197592 3.5876963 ]
 [6.46564877 4.7742237  5.0675282  3.57525181 4.45561728]] [[5.5  4.86 5.65 6.52 4.77]
 [4.77 6.58 5.77 4.53 5.54]
 [4.54 4.53 5.24 3.09 3.28]
 [4.44 3.99 5.31 4.09 3.59]
 [6.47 4.77 5.07 3.58 4.46]]


In [7]:
### Filtros Pandas
serie1 = pd.Series(data=np.random.randint(100,size=10))  ## Criando series
serie2 = pd.Series(data=np.random.randint(100,size=10))

((serie1 > 25) & (serie2 < 78))

0     True
1    False
2    False
3     True
4    False
5    False
6    False
7     True
8     True
9    False
dtype: bool

In [8]:
serie = [x for x in serie1 if x > 35 ]  ## Filtrando a partir de list comprehesions
serie

[50, 72, 38, 88, 59]

In [9]:
## Usando any e all
((serie1 > 25) & (serie2 < 78)).any()  # Ele filtra a partir de um unico valor dentro da estrutura é verdadeiro
((serie1 > 25) & (serie2 < 78)).all()  # Ele filtra se todos os valores dentro da estrutura sao verdadeiros

False

In [10]:
### Usando o isin
ser1 = pd.Series(list('abcdefghijlkmnopqrstuwyz'))  ## Cria uma lista em serie dos valores
ser1

ser1.isin(['a', 'e', 'i', 'o', 'u'])  ## O isin vai buscar os valores e retornar booleano
ser1[ser1.isin(['a', 'e', 'i', 'o', 'u'])]  ## O isin vai buscar os valores e retornar uma lista com os valores e seus indices

0     a
4     e
8     i
14    o
20    u
dtype: object

In [11]:
### Usando isnan e isnull - Retorna os valores nulos e not a number (NaN)
serie = pd.Series([1,2,3,np.nan,4,5,np.nan])  # Cria uma serie com valores reais e NaN
np.isnan(serie)  # Retorna somente os valores NAN
serie.isnull()  ## Retorna os valores NAN ou valores vazios
serie[serie.isnull()]  ## O valor retorna em uma lista dos valores NAN e os indices

3   NaN
6   NaN
dtype: float64

In [12]:
### Ex: Obtém os elementos da série 1 que não estão contidos na série 2
ser1 = pd.Series([1, 2, 3, 4, 5]) 
ser2 = pd.Series([4, 5, 6, 7, 8])

ser1[~ser1.isin(ser2.values)]  # Usando o ~ para trazer os valores diferentes, o isin busca os valores dentro de cada serie

0    1
1    2
2    3
dtype: int64

In [16]:
### Preenchimento de nulos com Pandas
## Criando uma serie com valores e alguns desses valores sendo NaN

np.random.seed(42)  ## Cria um array  na raiz da memoria
serie = pd.Series(np.random.randint(10, size=10))  ## Criamos uma serie de 10 numeros aleatorios de 0 a 10
serie.iloc[np.random.randint(10, size=3)] = np.nan  ## Usando o iloc para colocar 3 valores dentro da serie como NaN
serie

0    6.0
1    3.0
2    7.0
3    NaN
4    6.0
5    9.0
6    2.0
7    NaN
8    7.0
9    4.0
dtype: float64

In [17]:
### Preenchimento com Fillna
serie.fillna(0)  ## Usamos o fillna para mudar os valores NaN para o valor 0, todos os valores iram passar a ser NaN

0    6.0
1    3.0
2    7.0
3    0.0
4    6.0
5    9.0
6    2.0
7    0.0
8    7.0
9    4.0
dtype: float64

In [20]:
### Usando ffill e bfill para preenchimento
serie.ffill()  ## Usando o ffill os numeros NaN seram preenchidos com os valores a frente no caso o indice 3 será o valore do indice 2 sendo 7
serie.bfill()  ## Usando o bfill os numeros NaN seram preenchidos com os valores a atras no caso o indice 3 será o valore do indice 4 sendo 6

0    6.0
1    3.0
2    7.0
3    6.0
4    6.0
5    9.0
6    2.0
7    7.0
8    7.0
9    4.0
dtype: float64

In [32]:
#Ex: Abaixo carregamos os dados de índice de desenvolvimento humano para países Africanos. Você irá notar que há alguns valores nulos dentro dessa base. Preenche esses valores nulos com o valor médio da base.

serie_owid = pd.read_csv(
    "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/latest/owid-covid-latest.csv"
).loc[
    lambda f: (f["continent"] == "Africa")
    | (f["location"] == "Africa")
].set_index("iso_code")["human_development_index"]

serie = serie_owid.fillna(np.mean(serie_owid))  ## Com o fillna para substituir os valores NaN pela media dos valores da serie
serie

iso_code
OWID_AFR    0.560736
DZA         0.748000
AGO         0.581000
BEN         0.545000
BWA         0.735000
BFA         0.452000
BDI         0.433000
CMR         0.563000
CPV         0.665000
CAF         0.397000
TCD         0.398000
COM         0.554000
COG         0.574000
CIV         0.538000
COD         0.480000
DJI         0.524000
EGY         0.707000
GNQ         0.592000
ERI         0.459000
SWZ         0.611000
ETH         0.485000
GAB         0.703000
GMB         0.496000
GHA         0.611000
GIN         0.477000
GNB         0.480000
KEN         0.601000
LSO         0.527000
LBR         0.480000
LBY         0.724000
MDG         0.528000
MWI         0.483000
MLI         0.434000
MRT         0.546000
MUS         0.804000
MAR         0.686000
MOZ         0.456000
NAM         0.646000
NER         0.394000
NGA         0.539000
RWA         0.543000
SHN         0.560736
STP         0.625000
SEN         0.512000
SYC         0.796000
SLE         0.452000
SOM         0.560736
ZAF 